services:
  web:
    image: obaidlona/myapp:latest
    container_name: mysite
    ports:
      - "5000:8000"
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge